// GeneratedJourneyData.swift
// Changes: generated by scripts/export-game-constants.mjs. Do not edit by hand.

import CoreGraphics

enum GeneratedJourneyData {
    static let totalLevels = 42
    static let totalStars = 119
    static let starsPerLevel = 3
    static let pointsFromLevel = 4
    static let shieldsFromLevel = 5
    static let defaultBeatGapMs = 400
    static let lore = "A message came to us out of the dark, torn apart by the distance. Its pieces are still scattered along the way it travelled. NAV will guide you back to find who sent it."
    static let loreTitle = "The Call"
    static let loreEntryId = "signalCall"
    static let labIntro = "Hazard Lab — blooms, sweeps, push nodes, wind, portals, and wells. Practice only — nothing counts toward Journey."
    static let labGoalKm: CGFloat = 12000
    static let labDifficulty: CGFloat = 0.45
    static let labTypes = ["phase", "sweepGate", "repulsor", "driftCurrent", "wormhole", "blackhole"]
    static let emptyLogbook = "The pages are blank. Explore space. Then explore the space log."
    static let epiloguePrompt = "If you could say one thing to them, what would it be?"
    static let epiloguePromptPlaceholder = "Write it here."
    static let epilogueSubmitLabel = "Send it into the dark"
    static let epilogueSkipLabel = "Leave it unsaid"
    static let epilogueSkipLine = "Some things don't need words. A light appears for you either way."
    static let epilogueOfflineCard = "You answered the call."
    static let epilogueCounterCard = "You are the {N} to answer the call."
    static let epilogueFooterCard = "Follow @spaceswoosh.app to see what the others said."
    static let epilogueArcUnlockLines = ["You've unlocked Arc mode.", "Everybody hates it.", "Enjoy."]
    static let epilogueArcUnlockLabel = "Take the controls"
    static let epilogueInstagramHandle = "spaceswoosh.app"
    static let epilogueInstagramUrl = "https://www.instagram.com/spaceswoosh.app"

    static let chapters: [JourneyChapter] = [
        JourneyChapter(
            id: "learning",
            name: "First Light",
            blurb: "Learn the path. Listen to NAV.",
            from: 1,
            to: 6
        ),
        JourneyChapter(
            id: "journey",
            name: "The Long Way",
            blurb: "Follow the signal back to its source.",
            from: 7,
            to: 13
        ),
        JourneyChapter(
            id: "message",
            name: "Fragments",
            blurb: "The message begins to take shape.",
            from: 14,
            to: 23
        ),
        JourneyChapter(
            id: "tooold",
            name: "Deep Static",
            blurb: "The signal is older than it should be.",
            from: 24,
            to: 30
        ),
        JourneyChapter(
            id: "whowerethey",
            name: "The Senders",
            blurb: "Piece by piece, they come into focus.",
            from: 31,
            to: 36
        ),
        JourneyChapter(
            id: "earth",
            name: "The Source",
            blurb: "The trail ends at a single world.",
            from: 37,
            to: 40
        ),
        JourneyChapter(
            id: "homecoming",
            name: "Arrival",
            blurb: "Whatever waits, you are almost there.",
            from: 41,
            to: 42
        )
    ]

    static let levels: [JourneyLevelSpec] = [
        JourneyLevelSpec(
            level: 1,
            chapterId: "learning",
            chapterName: "First Light",
            difficulty: 0.16,
            goalKm: 1250,
            types: [],
            focusType: nil,
            pairTheme: nil,
            comboTheme: nil,
            encounterCount: 0,
            introduces: nil,
            sparklesTarget: 0,
            smashTarget: 0,
            starSlots: 1
        ),
        JourneyLevelSpec(
            level: 2,
            chapterId: "learning",
            chapterName: "First Light",
            difficulty: 0.22,
            goalKm: 2000,
            types: ["simple"],
            focusType: nil,
            pairTheme: nil,
            comboTheme: nil,
            encounterCount: 0,
            introduces: "simple",
            sparklesTarget: 0,
            smashTarget: 0,
            starSlots: 1
        ),
        JourneyLevelSpec(
            level: 3,
            chapterId: "learning",
            chapterName: "First Light",
            difficulty: 0.28,
            goalKm: 3000,
            types: ["simple", "moving"],
            focusType: "moving",
            pairTheme: nil,
            comboTheme: nil,
            encounterCount: 0,
            introduces: "moving",
            sparklesTarget: 0,
            smashTarget: 0,
            starSlots: 1
        ),
        JourneyLevelSpec(
            level: 4,
            chapterId: "learning",
            chapterName: "First Light",
            difficulty: 0.3,
            goalKm: 4000,
            types: ["simple", "moving"],
            focusType: "moving",
            pairTheme: nil,
            comboTheme: nil,
            encounterCount: 0,
            introduces: nil,
            sparklesTarget: 2,
            smashTarget: 0,
            starSlots: 2
        ),
        JourneyLevelSpec(
            level: 5,
            chapterId: "learning",
            chapterName: "First Light",
            difficulty: 0.32,
            goalKm: 7500,
            types: ["simple", "moving"],
            focusType: "moving",
            pairTheme: nil,
            comboTheme: nil,
            encounterCount: 0,
            introduces: nil,
            sparklesTarget: 7,
            smashTarget: 1,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 6,
            chapterId: "learning",
            chapterName: "First Light",
            difficulty: 0.42,
            goalKm: 8000,
            types: ["simple", "moving", "sideBarrier"],
            focusType: "sideBarrier",
            pairTheme: "moving",
            comboTheme: nil,
            encounterCount: 1,
            introduces: "sideBarrier",
            sparklesTarget: 7,
            smashTarget: 2,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 7,
            chapterId: "journey",
            chapterName: "The Long Way",
            difficulty: 0.42,
            goalKm: 8500,
            types: ["simple", "moving", "sideBarrier"],
            focusType: "moving",
            pairTheme: "sideBarrier",
            comboTheme: nil,
            encounterCount: 1,
            introduces: nil,
            sparklesTarget: 8,
            smashTarget: 2,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 8,
            chapterId: "journey",
            chapterName: "The Long Way",
            difficulty: 0.42,
            goalKm: 9000,
            types: ["simple", "moving", "sideBarrier"],
            focusType: "moving",
            pairTheme: "sideBarrier",
            comboTheme: nil,
            encounterCount: 1,
            introduces: nil,
            sparklesTarget: 8,
            smashTarget: 2,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 9,
            chapterId: "journey",
            chapterName: "The Long Way",
            difficulty: 0.5,
            goalKm: 9500,
            types: ["simple", "moving", "sideBarrier", "complex"],
            focusType: "complex",
            pairTheme: "moving",
            comboTheme: nil,
            encounterCount: 1,
            introduces: "complex",
            sparklesTarget: 9,
            smashTarget: 2,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 10,
            chapterId: "journey",
            chapterName: "The Long Way",
            difficulty: 0.5,
            goalKm: 11000,
            types: ["simple", "moving", "sideBarrier", "complex"],
            focusType: "complex",
            pairTheme: "moving",
            comboTheme: nil,
            encounterCount: 1,
            introduces: nil,
            sparklesTarget: 10,
            smashTarget: 2,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 11,
            chapterId: "journey",
            chapterName: "The Long Way",
            difficulty: 0.5,
            goalKm: 11500,
            types: ["simple", "moving", "sideBarrier", "complex"],
            focusType: "moving",
            pairTheme: "complex",
            comboTheme: nil,
            encounterCount: 1,
            introduces: nil,
            sparklesTarget: 11,
            smashTarget: 2,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 12,
            chapterId: "journey",
            chapterName: "The Long Way",
            difficulty: 0.58,
            goalKm: 12000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting"],
            focusType: "shooting",
            pairTheme: "moving",
            comboTheme: nil,
            encounterCount: 1,
            introduces: "shooting",
            sparklesTarget: 11,
            smashTarget: 2,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 13,
            chapterId: "journey",
            chapterName: "The Long Way",
            difficulty: 0.58,
            goalKm: 12500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting"],
            focusType: "complex",
            pairTheme: "shooting",
            comboTheme: nil,
            encounterCount: 1,
            introduces: nil,
            sparklesTarget: 12,
            smashTarget: 3,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 14,
            chapterId: "message",
            chapterName: "Fragments",
            difficulty: 0.58,
            goalKm: 13000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting"],
            focusType: "shooting",
            pairTheme: "moving",
            comboTheme: nil,
            encounterCount: 1,
            introduces: nil,
            sparklesTarget: 12,
            smashTarget: 3,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 15,
            chapterId: "message",
            chapterName: "Fragments",
            difficulty: 0.62,
            goalKm: 14500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent"],
            focusType: "driftCurrent",
            pairTheme: "moving",
            comboTheme: nil,
            encounterCount: 1,
            introduces: "driftCurrent",
            sparklesTarget: 14,
            smashTarget: 3,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 16,
            chapterId: "message",
            chapterName: "Fragments",
            difficulty: 0.62,
            goalKm: 15000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent"],
            focusType: "complex",
            pairTheme: "shooting",
            comboTheme: nil,
            encounterCount: 1,
            introduces: nil,
            sparklesTarget: 14,
            smashTarget: 3,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 17,
            chapterId: "message",
            chapterName: "Fragments",
            difficulty: 0.68,
            goalKm: 15500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating"],
            focusType: "pulsating",
            pairTheme: "moving",
            comboTheme: nil,
            encounterCount: 1,
            introduces: "pulsating",
            sparklesTarget: 15,
            smashTarget: 3,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 18,
            chapterId: "message",
            chapterName: "Fragments",
            difficulty: 0.68,
            goalKm: 16000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating"],
            focusType: "complex",
            pairTheme: "shooting",
            comboTheme: nil,
            encounterCount: 1,
            introduces: nil,
            sparklesTarget: 15,
            smashTarget: 3,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 19,
            chapterId: "message",
            chapterName: "Fragments",
            difficulty: 0.68,
            goalKm: 16500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating"],
            focusType: "shooting",
            pairTheme: "pulsating",
            comboTheme: nil,
            encounterCount: 1,
            introduces: nil,
            sparklesTarget: 16,
            smashTarget: 3,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 20,
            chapterId: "message",
            chapterName: "Fragments",
            difficulty: 0.72,
            goalKm: 18000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase"],
            focusType: "phase",
            pairTheme: "moving",
            comboTheme: "driftCurrent",
            encounterCount: 1,
            introduces: "phase",
            sparklesTarget: 17,
            smashTarget: 4,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 21,
            chapterId: "message",
            chapterName: "Fragments",
            difficulty: 0.72,
            goalKm: 18500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase"],
            focusType: "complex",
            pairTheme: "shooting",
            comboTheme: "phase",
            encounterCount: 1,
            introduces: nil,
            sparklesTarget: 18,
            smashTarget: 4,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 22,
            chapterId: "message",
            chapterName: "Fragments",
            difficulty: 0.78,
            goalKm: 19000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole"],
            focusType: "wormhole",
            pairTheme: "moving",
            comboTheme: "driftCurrent",
            encounterCount: 1,
            introduces: "wormhole",
            sparklesTarget: 18,
            smashTarget: 4,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 23,
            chapterId: "message",
            chapterName: "Fragments",
            difficulty: 0.78,
            goalKm: 19500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole"],
            focusType: "complex",
            pairTheme: "shooting",
            comboTheme: "phase",
            encounterCount: 1,
            introduces: nil,
            sparklesTarget: 19,
            smashTarget: 4,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 24,
            chapterId: "tooold",
            chapterName: "Deep Static",
            difficulty: 0.78,
            goalKm: 20000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole"],
            focusType: "shooting",
            pairTheme: "pulsating",
            comboTheme: "wormhole",
            encounterCount: 1,
            introduces: nil,
            sparklesTarget: 19,
            smashTarget: 4,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 25,
            chapterId: "tooold",
            chapterName: "Deep Static",
            difficulty: 0.84,
            goalKm: 21500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor"],
            focusType: "repulsor",
            pairTheme: "moving",
            comboTheme: "driftCurrent",
            encounterCount: 2,
            introduces: "repulsor",
            sparklesTarget: 21,
            smashTarget: 4,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 26,
            chapterId: "tooold",
            chapterName: "Deep Static",
            difficulty: 0.84,
            goalKm: 22000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor"],
            focusType: "complex",
            pairTheme: "shooting",
            comboTheme: "phase",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 21,
            smashTarget: 4,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 27,
            chapterId: "tooold",
            chapterName: "Deep Static",
            difficulty: 0.9,
            goalKm: 22500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole"],
            focusType: "blackhole",
            pairTheme: "moving",
            comboTheme: "driftCurrent",
            encounterCount: 2,
            introduces: "blackhole",
            sparklesTarget: 22,
            smashTarget: 5,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 28,
            chapterId: "tooold",
            chapterName: "Deep Static",
            difficulty: 0.9,
            goalKm: 23000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole"],
            focusType: "complex",
            pairTheme: "shooting",
            comboTheme: "phase",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 22,
            smashTarget: 5,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 29,
            chapterId: "tooold",
            chapterName: "Deep Static",
            difficulty: 0.9,
            goalKm: 23500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole"],
            focusType: "shooting",
            pairTheme: "pulsating",
            comboTheme: "wormhole",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 23,
            smashTarget: 5,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 30,
            chapterId: "tooold",
            chapterName: "Deep Static",
            difficulty: 0.9,
            goalKm: 25000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole"],
            focusType: "driftCurrent",
            pairTheme: "moving",
            comboTheme: "repulsor",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 24,
            smashTarget: 5,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 31,
            chapterId: "whowerethey",
            chapterName: "The Senders",
            difficulty: 0.95,
            goalKm: 25500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole", "sweepGate"],
            focusType: "sweepGate",
            pairTheme: "moving",
            comboTheme: "driftCurrent",
            encounterCount: 2,
            introduces: "sweepGate",
            sparklesTarget: 25,
            smashTarget: 5,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 32,
            chapterId: "whowerethey",
            chapterName: "The Senders",
            difficulty: 0.95,
            goalKm: 26000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole", "sweepGate"],
            focusType: "complex",
            pairTheme: "shooting",
            comboTheme: "phase",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 25,
            smashTarget: 5,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 33,
            chapterId: "whowerethey",
            chapterName: "The Senders",
            difficulty: 0.95,
            goalKm: 26500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole", "sweepGate"],
            focusType: "shooting",
            pairTheme: "pulsating",
            comboTheme: "wormhole",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 26,
            smashTarget: 5,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 34,
            chapterId: "whowerethey",
            chapterName: "The Senders",
            difficulty: 1,
            goalKm: 27000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole", "sweepGate"],
            focusType: "moving",
            pairTheme: "shooting",
            comboTheme: "pulsating",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 26,
            smashTarget: 6,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 35,
            chapterId: "whowerethey",
            chapterName: "The Senders",
            difficulty: 1,
            goalKm: 28500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole", "sweepGate"],
            focusType: "complex",
            pairTheme: "shooting",
            comboTheme: "phase",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 28,
            smashTarget: 6,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 36,
            chapterId: "whowerethey",
            chapterName: "The Senders",
            difficulty: 1,
            goalKm: 29000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole", "sweepGate"],
            focusType: "shooting",
            pairTheme: "pulsating",
            comboTheme: "wormhole",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 28,
            smashTarget: 6,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 37,
            chapterId: "earth",
            chapterName: "The Source",
            difficulty: 1,
            goalKm: 29500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole", "sweepGate"],
            focusType: "driftCurrent",
            pairTheme: "moving",
            comboTheme: "repulsor",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 29,
            smashTarget: 6,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 38,
            chapterId: "earth",
            chapterName: "The Source",
            difficulty: 1,
            goalKm: 30000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole", "sweepGate"],
            focusType: "pulsating",
            pairTheme: "shooting",
            comboTheme: "blackhole",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 29,
            smashTarget: 6,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 39,
            chapterId: "earth",
            chapterName: "The Source",
            difficulty: 1,
            goalKm: 30500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole", "sweepGate"],
            focusType: "phase",
            pairTheme: "shooting",
            comboTheme: "sweepGate",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 30,
            smashTarget: 6,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 40,
            chapterId: "earth",
            chapterName: "The Source",
            difficulty: 1,
            goalKm: 32000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole", "sweepGate"],
            focusType: "wormhole",
            pairTheme: "moving",
            comboTheme: "complex",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 31,
            smashTarget: 6,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 41,
            chapterId: "homecoming",
            chapterName: "Arrival",
            difficulty: 1,
            goalKm: 32500,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole", "sweepGate"],
            focusType: "repulsor",
            pairTheme: "shooting",
            comboTheme: "complex",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 32,
            smashTarget: 6,
            starSlots: 3
        ),
        JourneyLevelSpec(
            level: 42,
            chapterId: "homecoming",
            chapterName: "Arrival",
            difficulty: 1,
            goalKm: 34000,
            types: ["simple", "moving", "sideBarrier", "complex", "shooting", "driftCurrent", "pulsating", "phase", "wormhole", "repulsor", "blackhole", "sweepGate"],
            focusType: "blackhole",
            pairTheme: "complex",
            comboTheme: "driftCurrent",
            encounterCount: 2,
            introduces: nil,
            sparklesTarget: 33,
            smashTarget: 6,
            starSlots: 3
        )
    ]

    static let messages: [Int: String] = [
        1: "There you are. Tap once. Let me see you turn.",
        2: "Rocks ahead. Don't look at them. Look at the room between them.",
        3: "That one is moving. Learn its path before you choose yours.",
        4: "See the blue light? Take it. Blue is fuel out here. It keeps you moving.",
        5: "Take the shield. For a few seconds... you can survive what should stop you.",
        6: "Good. You can fly. Now let's find whoever called us.",
        7: "We're retracing the signal's path. The old relay lanes fold the distance for us.",
        8: "The transmission crossed thousands of systems. Most of it didn't survive.",
        9: "There's an old relay ahead. Pass close. It may still remember part of the signal.",
        10: "It does. A sequence of prime numbers. Someone wanted us to know this wasn't noise.",
        11: "They began with counting. One, two, three, all the way to ten. As if to say: we think, too.",
        12: "They were trying very hard... not to be missed.",
        13: "I like them already. Keep going.",
        14: "Another relay. This fragment describes their star. Yellow. Ordinary. Stable.",
        15: "Eight planets. They lived on the third.",
        16: "Mostly ocean. One moon. A thin little atmosphere.",
        17: "They sent pictures too. The encoding is damaged... but I'm working on it.",
        18: "There are buildings. Machines. Faces, I think.",
        19: "They drew the shape they're built from. A twist of it, over and over. Their own chemistry, handed to strangers.",
        20: "And music. They put music in a message to strangers. That may be my favourite thing about them.",
        21: "Not only music. Sounds. Rain. A heartbeat. Someone, somewhere, laughing.",
        22: "They even drew a map. Here is our star, here is our world. Come find us. So trusting.",
        23: "They only sent it once. A hello into the dark, with no hope of an answer. And they sent it anyway.",
        24: "I've finished dating the transmission. There's a problem.",
        25: "It was already more than a million years old... when we received it.",
        26: "Don't stop. Old doesn't mean gone. Not necessarily.",
        27: "No later transmissions appear anywhere along the route. One message, and then silence.",
        28: "A civilization loud enough to send this... should have left something else behind.",
        29: "I'm searching. Keep flying.",
        30: "Nothing. There's nothing.",
        31: "I recovered part of their anatomy. Two arms. Two legs. Upright.",
        32: "Five digits on each hand. Rather useful design, actually.",
        33: "Another image cleared. Blue sky. Green vegetation. White clouds.",
        34: "Fascinating. I found their name for the planet. Translation is still resolving.",
        35: "Their star has a name too. One syllable.",
        36: "Sol. They called it Sol.",
        37: "The planet was called Earth.",
        38: "I found them in the old archive... Their entire entry is one word. Unremarkable.",
        39: "Unremarkable. They sang into the dark, and we filed them under \"unremarkable.\"",
        40: "I can see their sun from here. Yellow. Ordinary. Just as they said.",
        41: "Sol is ahead. No artificial signals. No active structures.",
        42: "Earth is still there. The ones who called... are not."
    ]

    static let introBeats: [Int: [IntroBeat]] = [
        1: [
        IntroBeat(text: "There you are.", gapAfterMs: 400),
        IntroBeat(text: "Tap once.", gapAfterMs: 400),
        IntroBeat(text: "Let me see you turn.", gapAfterMs: 400)
        ],
        2: [
        IntroBeat(text: "Rocks ahead.", gapAfterMs: 400),
        IntroBeat(text: "Don't look at them.", gapAfterMs: 400),
        IntroBeat(text: "Look at the room between them.", gapAfterMs: 400)
        ],
        3: [
        IntroBeat(text: "That one is moving.", gapAfterMs: 400),
        IntroBeat(text: "Learn its path before you choose yours.", gapAfterMs: 400)
        ],
        4: [
        IntroBeat(text: "See the blue light?", gapAfterMs: 400),
        IntroBeat(text: "Take it.", gapAfterMs: 400),
        IntroBeat(text: "Blue is fuel out here.", gapAfterMs: 400),
        IntroBeat(text: "It keeps you moving.", gapAfterMs: 400)
        ],
        5: [
        IntroBeat(text: "Take the shield.", gapAfterMs: 400),
        IntroBeat(text: "For a few seconds... you can survive what should stop you.", gapAfterMs: 400)
        ],
        6: [
        IntroBeat(text: "Good.", gapAfterMs: 600),
        IntroBeat(text: "You can fly.", gapAfterMs: 500),
        IntroBeat(text: "Now let's find whoever called us.", gapAfterMs: 400)
        ],
        7: [
        IntroBeat(text: "We're retracing the signal's path.", gapAfterMs: 500),
        IntroBeat(text: "The old relay lanes fold the distance for us.", gapAfterMs: 400)
        ],
        8: [
        IntroBeat(text: "The transmission crossed thousands of systems.", gapAfterMs: 600),
        IntroBeat(text: "Most of it didn't survive.", gapAfterMs: 400)
        ],
        9: [
        IntroBeat(text: "There's an old relay ahead.", gapAfterMs: 500),
        IntroBeat(text: "Pass close.", gapAfterMs: 400),
        IntroBeat(text: "It may still remember part of the signal.", gapAfterMs: 400)
        ],
        10: [
        IntroBeat(text: "It does.", gapAfterMs: 500),
        IntroBeat(text: "A sequence of prime numbers.", gapAfterMs: 500),
        IntroBeat(text: "Someone wanted us to know this wasn't noise.", gapAfterMs: 400)
        ],
        11: [
        IntroBeat(text: "They began with counting.", gapAfterMs: 500),
        IntroBeat(text: "One, two, three, all the way to ten.", gapAfterMs: 600),
        IntroBeat(text: "As if to say: we think, too.", gapAfterMs: 400)
        ],
        12: [
        IntroBeat(text: "They were trying very hard...", gapAfterMs: 500),
        IntroBeat(text: "not to be missed.", gapAfterMs: 400)
        ],
        13: [
        IntroBeat(text: "I like them already.", gapAfterMs: 500),
        IntroBeat(text: "Keep going.", gapAfterMs: 400)
        ],
        14: [
        IntroBeat(text: "Another relay.", gapAfterMs: 500),
        IntroBeat(text: "This fragment describes their star.", gapAfterMs: 500),
        IntroBeat(text: "Yellow.", gapAfterMs: 400),
        IntroBeat(text: "Ordinary.", gapAfterMs: 400),
        IntroBeat(text: "Stable.", gapAfterMs: 400)
        ],
        15: [
        IntroBeat(text: "Eight planets.", gapAfterMs: 600),
        IntroBeat(text: "They lived on the third.", gapAfterMs: 400)
        ],
        16: [
        IntroBeat(text: "Mostly ocean.", gapAfterMs: 500),
        IntroBeat(text: "One moon.", gapAfterMs: 500),
        IntroBeat(text: "A thin little atmosphere.", gapAfterMs: 400)
        ],
        17: [
        IntroBeat(text: "They sent pictures too.", gapAfterMs: 500),
        IntroBeat(text: "The encoding is damaged... but I'm working on it.", gapAfterMs: 400)
        ],
        18: [
        IntroBeat(text: "There are buildings.", gapAfterMs: 400),
        IntroBeat(text: "Machines.", gapAfterMs: 500),
        IntroBeat(text: "Faces, I think.", gapAfterMs: 400)
        ],
        19: [
        IntroBeat(text: "They drew the shape they're built from.", gapAfterMs: 500),
        IntroBeat(text: "A twist of it, over and over.", gapAfterMs: 600),
        IntroBeat(text: "Their own chemistry, handed to strangers.", gapAfterMs: 400)
        ],
        20: [
        IntroBeat(text: "And music.", gapAfterMs: 600),
        IntroBeat(text: "They put music in a message to strangers.", gapAfterMs: 600),
        IntroBeat(text: "That may be my favourite thing about them.", gapAfterMs: 400)
        ],
        21: [
        IntroBeat(text: "Not only music.", gapAfterMs: 500),
        IntroBeat(text: "Sounds.", gapAfterMs: 400),
        IntroBeat(text: "Rain.", gapAfterMs: 400),
        IntroBeat(text: "A heartbeat.", gapAfterMs: 500),
        IntroBeat(text: "Someone, somewhere, laughing.", gapAfterMs: 400)
        ],
        22: [
        IntroBeat(text: "They even drew a map.", gapAfterMs: 500),
        IntroBeat(text: "Here is our star, here is our world.", gapAfterMs: 500),
        IntroBeat(text: "Come find us.", gapAfterMs: 600),
        IntroBeat(text: "So trusting.", gapAfterMs: 400)
        ],
        23: [
        IntroBeat(text: "They only sent it once.", gapAfterMs: 600),
        IntroBeat(text: "A hello into the dark, with no hope of an answer.", gapAfterMs: 800),
        IntroBeat(text: "And they sent it anyway.", gapAfterMs: 400)
        ],
        24: [
        IntroBeat(text: "I've finished dating the transmission.", gapAfterMs: 700),
        IntroBeat(text: "There's a problem.", gapAfterMs: 400)
        ],
        25: [
        IntroBeat(text: "It was already more than a million years old...", gapAfterMs: 600),
        IntroBeat(text: "when we received it.", gapAfterMs: 400)
        ],
        26: [
        IntroBeat(text: "Don't stop.", gapAfterMs: 500),
        IntroBeat(text: "Old doesn't mean gone.", gapAfterMs: 600),
        IntroBeat(text: "Not necessarily.", gapAfterMs: 400)
        ],
        27: [
        IntroBeat(text: "No later transmissions appear anywhere along the route.", gapAfterMs: 800),
        IntroBeat(text: "One message, and then silence.", gapAfterMs: 400)
        ],
        28: [
        IntroBeat(text: "A civilization loud enough to send this...", gapAfterMs: 500),
        IntroBeat(text: "should have left something else behind.", gapAfterMs: 400)
        ],
        29: [
        IntroBeat(text: "I'm searching.", gapAfterMs: 500),
        IntroBeat(text: "Keep flying.", gapAfterMs: 400)
        ],
        30: [
        IntroBeat(text: "Nothing.", gapAfterMs: 2000),
        IntroBeat(text: "There's nothing.", gapAfterMs: 400)
        ],
        31: [
        IntroBeat(text: "I recovered part of their anatomy.", gapAfterMs: 500),
        IntroBeat(text: "Two arms.", gapAfterMs: 400),
        IntroBeat(text: "Two legs.", gapAfterMs: 400),
        IntroBeat(text: "Upright.", gapAfterMs: 400)
        ],
        32: [
        IntroBeat(text: "Five digits on each hand.", gapAfterMs: 500),
        IntroBeat(text: "Rather useful design, actually.", gapAfterMs: 400)
        ],
        33: [
        IntroBeat(text: "Another image cleared.", gapAfterMs: 500),
        IntroBeat(text: "Blue sky.", gapAfterMs: 400),
        IntroBeat(text: "Green vegetation.", gapAfterMs: 400),
        IntroBeat(text: "White clouds.", gapAfterMs: 400)
        ],
        34: [
        IntroBeat(text: "Fascinating.", gapAfterMs: 400),
        IntroBeat(text: "I found their name for the planet.", gapAfterMs: 500),
        IntroBeat(text: "Translation is still resolving.", gapAfterMs: 400)
        ],
        35: [
        IntroBeat(text: "Their star has a name too.", gapAfterMs: 600),
        IntroBeat(text: "One syllable.", gapAfterMs: 400)
        ],
        36: [
        IntroBeat(text: "Sol.", gapAfterMs: 800),
        IntroBeat(text: "They called it Sol.", gapAfterMs: 400)
        ],
        37: [
        IntroBeat(text: "The planet was called Earth.", gapAfterMs: 400)
        ],
        38: [
        IntroBeat(text: "I found them in the old archive...", gapAfterMs: 700),
        IntroBeat(text: "Their entire entry is one word.", gapAfterMs: 600),
        IntroBeat(text: "Unremarkable.", gapAfterMs: 400)
        ],
        39: [
        IntroBeat(text: "Unremarkable.", gapAfterMs: 900),
        IntroBeat(text: "They sang into the dark, and we filed them under \"unremarkable.\"", gapAfterMs: 400)
        ],
        40: [
        IntroBeat(text: "I can see their sun from here.", gapAfterMs: 600),
        IntroBeat(text: "Yellow.", gapAfterMs: 400),
        IntroBeat(text: "Ordinary.", gapAfterMs: 400),
        IntroBeat(text: "Just as they said.", gapAfterMs: 400)
        ],
        41: [
        IntroBeat(text: "Sol is ahead.", gapAfterMs: 600),
        IntroBeat(text: "No artificial signals.", gapAfterMs: 500),
        IntroBeat(text: "No active structures.", gapAfterMs: 400)
        ],
        42: [
        IntroBeat(text: "Earth is still there.", gapAfterMs: 1000),
        IntroBeat(text: "The ones who called...", gapAfterMs: 600),
        IntroBeat(text: "are not.", gapAfterMs: 400)
        ]
    ]

    static let firstBoopBeats: [IntroBeat] = [
        IntroBeat(text: "The walls forgive.", gapAfterMs: 400),
        IntroBeat(text: "Little else out here does.", gapAfterMs: 400)
    ]

    static let epilogueOpen: [IntroBeat] = [
        IntroBeat(text: "They can't hear us anymore.", gapAfterMs: 900),
        IntroBeat(text: "But we can still answer.", gapAfterMs: 400)
    ]

    static let epilogueSkip: [IntroBeat] = [
        IntroBeat(text: "Some things don't need words.", gapAfterMs: 700),
        IntroBeat(text: "A light appears for you either way.", gapAfterMs: 400)
    ]

    static let logbookCategories: [LogbookCategorySpec] = [
        LogbookCategorySpec(id: "obstacles", label: "Obstacles"),
        LogbookCategorySpec(id: "boosts", label: "Boosts"),
        LogbookCategorySpec(id: "levels", label: "Journey"),
        LogbookCategorySpec(id: "void", label: "From the Void")
    ]

    static let logbookEntries: [LogbookEntrySpec] = [
        LogbookEntrySpec(
            id: "asteroidCircle",
            category: "obstacles",
            name: "Round Asteroid",
            definition: "A solid ink disc. Common, round, and lethal on contact.",
            remark: "Geometry at its most agreeable.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "asteroidTriangle",
            category: "obstacles",
            name: "Shard Asteroid",
            definition: "A triangular ink shard. Corners catch you on a glance.",
            remark: "Three points. One opinion.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "asteroidSquare",
            category: "obstacles",
            name: "Block Asteroid",
            definition: "A square ink block. Right angles in the flight path.",
            remark: "Right angles in a wrong place.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "sideBarrier",
            category: "obstacles",
            name: "Side Barrier",
            definition: "Paired walls that pinch the corridor. Hit them and you are done.",
            remark: "The edges of the page also bite.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "complex",
            category: "obstacles",
            name: "Complex Asteroid",
            definition: "A core with orbiting moons. Smash a moon or the core; both kill.",
            remark: "One rock. Several opinions.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "moving",
            category: "obstacles",
            name: "Moving Asteroid",
            definition: "A pentagon that drifts left and right. Do not trust where it was.",
            remark: "Inertia has hobbies.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "shooting",
            category: "obstacles",
            name: "Shooting Asteroid",
            definition: "A star that fires shots. Body and shots both kill without a shield.",
            remark: "It objects at range. Noted.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "pulsating",
            category: "obstacles",
            name: "Pulsating Asteroid",
            definition: "A disc that grows and shrinks. A gap that fits now may close next beat.",
            remark: "Breathing rock. Illogical, yet consistent.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "phase",
            category: "obstacles",
            name: "Square Bloom",
            definition: "One square blooms into four spinning ones. The shove is real; contact still kills.",
            remark: "Geometry that inhales.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "sweepGate",
            category: "obstacles",
            name: "Sweep Gate",
            definition: "A slim ink blade that sweeps the corridor. Time the gap. No style bonus here.",
            remark: "A clock with teeth.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "repulsor",
            category: "obstacles",
            name: "Repulsor Node",
            definition: "A solid core with a wide push field. The core kills; the shove still logs contact.",
            remark: "Personal space, enforced.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "driftCurrent",
            category: "obstacles",
            name: "Drift Current",
            definition: "A full-width band of shear lines. Inside it, the ship is shoved left or right.",
            remark: "Weather with opinions.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "blackhole",
            category: "obstacles",
            name: "Black Hole",
            definition: "A well that pulls you toward its core. The body is solid; the pull still logs contact.",
            remark: "Attraction without consent. Classic.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "spaceBoop",
            category: "obstacles",
            name: "Space BOOP",
            definition: "The ship hits a screen edge. It compresses, squeaks, and turns sharply.",
            remark: "The universe has borders. They squeak.",
            unlockMode: "instant"
        ),
        LogbookEntrySpec(
            id: "shield",
            category: "boosts",
            name: "Deflector Shield",
            definition: "A Signal-Blue envelope for a few seconds. Hits smash rocks instead of the ship.",
            remark: "Temporary immortality. Do not file under permanent.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "wormhole",
            category: "boosts",
            name: "Wormhole Gate",
            definition: "Paired rings. Cross the entry to jump to the exit and gain a brief shield.",
            remark: "You arrive elsewhere. The rocks do not apologize.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "wallBoost",
            category: "boosts",
            name: "Wall Boost",
            definition: "A thin Signal-Blue edge slab on deep runs. Bank into it for a shield and a speed burst.",
            remark: "The wall finally has manners.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "pointsSparkle",
            category: "boosts",
            name: "Fuel Sparkle",
            definition: "A Signal-Blue diamond that refills fuel. Miss too many and the engines die.",
            remark: "Brightness you can burn.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "styleSwoosh",
            category: "boosts",
            name: "Style Swoosh",
            definition: "Thread a tight gap between two obstacles. You get style points and a blue flourish.",
            remark: "Precision is its own currency.",
            unlockMode: "instant"
        ),
        LogbookEntrySpec(
            id: "deflectorSmash",
            category: "boosts",
            name: "Deflector Smash",
            definition: "A shielded hit that pulverizes a rock. Debris flies; points and the smash count go up.",
            remark: "Manners optional. Physics mandatory.",
            unlockMode: "instant"
        ),
        LogbookEntrySpec(
            id: "finishGate",
            category: "boosts",
            name: "Finish Gate",
            definition: "A Signal-Blue stream between two wall emitters. Cross it to clear the Journey level.",
            remark: "The stream is not a suggestion.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "signalCall",
            category: "levels",
            name: "The Call",
            definition: "A message came to us out of the dark, torn apart by the distance. Its pieces are still scattered along the way it travelled. NAV will guide you back to find who sent it.",
            remark: "Keep moving. Listen to the voice.",
            unlockMode: "instant"
        ),
        LogbookEntrySpec(
            id: "level_1",
            category: "levels",
            name: "Day 1",
            definition: "There you are. Tap once. Let me see you turn.",
            remark: "Early flight. The voice is teaching.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_2",
            category: "levels",
            name: "Day 2",
            definition: "Rocks ahead. Don't look at them. Look at the room between them.",
            remark: "Early flight. The voice is teaching.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_3",
            category: "levels",
            name: "Day 3",
            definition: "That one is moving. Learn its path before you choose yours.",
            remark: "Early flight. The voice is teaching.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_4",
            category: "levels",
            name: "Day 4",
            definition: "See the blue light? Take it. Blue is fuel out here. It keeps you moving.",
            remark: "Early flight. The voice is teaching.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_5",
            category: "levels",
            name: "Day 5",
            definition: "Take the shield. For a few seconds... you can survive what should stop you.",
            remark: "Early flight. The voice is teaching.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_6",
            category: "levels",
            name: "Day 6",
            definition: "Good. You can fly. Now let's find whoever called us.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_7",
            category: "levels",
            name: "Day 7",
            definition: "We're retracing the signal's path. The old relay lanes fold the distance for us.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_8",
            category: "levels",
            name: "Day 8",
            definition: "The transmission crossed thousands of systems. Most of it didn't survive.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_9",
            category: "levels",
            name: "Day 9",
            definition: "There's an old relay ahead. Pass close. It may still remember part of the signal.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_10",
            category: "levels",
            name: "Day 10",
            definition: "It does. A sequence of prime numbers. Someone wanted us to know this wasn't noise.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_11",
            category: "levels",
            name: "Day 11",
            definition: "They began with counting. One, two, three, all the way to ten. As if to say: we think, too.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_12",
            category: "levels",
            name: "Day 12",
            definition: "They were trying very hard... not to be missed.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_13",
            category: "levels",
            name: "Day 13",
            definition: "I like them already. Keep going.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_14",
            category: "levels",
            name: "Day 14",
            definition: "Another relay. This fragment describes their star. Yellow. Ordinary. Stable.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_15",
            category: "levels",
            name: "Day 15",
            definition: "Eight planets. They lived on the third.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_16",
            category: "levels",
            name: "Day 16",
            definition: "Mostly ocean. One moon. A thin little atmosphere.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_17",
            category: "levels",
            name: "Day 17",
            definition: "They sent pictures too. The encoding is damaged... but I'm working on it.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_18",
            category: "levels",
            name: "Day 18",
            definition: "There are buildings. Machines. Faces, I think.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_19",
            category: "levels",
            name: "Day 19",
            definition: "They drew the shape they're built from. A twist of it, over and over. Their own chemistry, handed to strangers.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_20",
            category: "levels",
            name: "Day 20",
            definition: "And music. They put music in a message to strangers. That may be my favourite thing about them.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_21",
            category: "levels",
            name: "Day 21",
            definition: "Not only music. Sounds. Rain. A heartbeat. Someone, somewhere, laughing.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_22",
            category: "levels",
            name: "Day 22",
            definition: "They even drew a map. Here is our star, here is our world. Come find us. So trusting.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_23",
            category: "levels",
            name: "Day 23",
            definition: "They only sent it once. A hello into the dark, with no hope of an answer. And they sent it anyway.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_24",
            category: "levels",
            name: "Day 24",
            definition: "I've finished dating the transmission. There's a problem.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_25",
            category: "levels",
            name: "Day 25",
            definition: "It was already more than a million years old... when we received it.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_26",
            category: "levels",
            name: "Day 26",
            definition: "Don't stop. Old doesn't mean gone. Not necessarily.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_27",
            category: "levels",
            name: "Day 27",
            definition: "No later transmissions appear anywhere along the route. One message, and then silence.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_28",
            category: "levels",
            name: "Day 28",
            definition: "A civilization loud enough to send this... should have left something else behind.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_29",
            category: "levels",
            name: "Day 29",
            definition: "I'm searching. Keep flying.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_30",
            category: "levels",
            name: "Day 30",
            definition: "Nothing. There's nothing.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_31",
            category: "levels",
            name: "Day 31",
            definition: "I recovered part of their anatomy. Two arms. Two legs. Upright.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_32",
            category: "levels",
            name: "Day 32",
            definition: "Five digits on each hand. Rather useful design, actually.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_33",
            category: "levels",
            name: "Day 33",
            definition: "Another image cleared. Blue sky. Green vegetation. White clouds.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_34",
            category: "levels",
            name: "Day 34",
            definition: "Fascinating. I found their name for the planet. Translation is still resolving.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_35",
            category: "levels",
            name: "Day 35",
            definition: "Their star has a name too. One syllable.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_36",
            category: "levels",
            name: "Day 36",
            definition: "Sol. They called it Sol.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_37",
            category: "levels",
            name: "Day 37",
            definition: "The planet was called Earth.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_38",
            category: "levels",
            name: "Day 38",
            definition: "I found them in the old archive... Their entire entry is one word. Unremarkable.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_39",
            category: "levels",
            name: "Day 39",
            definition: "Unremarkable. They sang into the dark, and we filed them under \"unremarkable.\"",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_40",
            category: "levels",
            name: "Day 40",
            definition: "I can see their sun from here. Yellow. Ordinary. Just as they said.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_41",
            category: "levels",
            name: "Day 41",
            definition: "Sol is ahead. No artificial signals. No active structures.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        ),
        LogbookEntrySpec(
            id: "level_42",
            category: "levels",
            name: "Day 42",
            definition: "Earth is still there. The ones who called... are not.",
            remark: "Logged from the navigator’s open channel.",
            unlockMode: "observeThenInteract"
        )
    ]

    static let observedPending: [String] = [
        "Sensors registered the phenomenon. Interaction required before a full reading.",
        "Visual contact confirmed. Understanding remains provisional.",
        "Catalogued by outline only. Direct contact will complete the entry.",
        "Observed. The definition is incomplete until we touch it, carefully."
    ]

    static let emptyCategory: [String: String] = [
        "obstacles": "No contacts logged. The rocks are patient.",
        "boosts": "No boosts recorded. Opportunity is still theoretical.",
        "levels": "No flight reports filed. Begin a Journey.",
        "void": "No transmissions. Sensors remain optimistic."
    ]

    static let encounterCatalog: [EncounterRecipe] = [
        EncounterRecipe(
            id: "bloomSqueeze",
            family: "bloom",
            requires: ["phase", "sideBarrier"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "sideBarrier", lane: nil)]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "phase", lane: "center")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "simple", lane: "left"), EncounterSlot(type: "simple", lane: "right")]),
                EncounterBeat(kind: "gap", frac: 0.55, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "crossfire",
            family: "cross",
            requires: ["shooting", "moving"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "shooting", lane: "left"), EncounterSlot(type: "moving", lane: "right")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "moving", lane: "left"), EncounterSlot(type: "shooting", lane: "right")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "pulseGate",
            family: "pulse",
            requires: ["pulsating", "sideBarrier"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "sideBarrier", lane: nil)]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "pulsating", lane: "center")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "needleWeave",
            family: "corridor",
            requires: ["sideBarrier", "moving", "shooting"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "sideBarrier", lane: nil)]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "moving", lane: "center")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "shooting", lane: "left")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "wallWeave",
            family: "corridor",
            requires: ["sideBarrier", "moving"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "sideBarrier", lane: nil)]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "moving", lane: "center")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "simple", lane: "left"), EncounterSlot(type: "simple", lane: "right")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "windWeave",
            family: "wind",
            requires: ["driftCurrent", "moving", "shooting"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "driftCurrent", lane: nil)]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "moving", lane: "left"), EncounterSlot(type: "shooting", lane: "right")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "portalAmbush",
            family: "portal",
            requires: ["wormhole", "moving", "shooting"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "wormhole", lane: nil)]),
                EncounterBeat(kind: "gap", frac: 0.85, slots: []),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "moving", lane: "left"), EncounterSlot(type: "shooting", lane: "right")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "twinPush",
            family: "push",
            requires: ["repulsor", "moving"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "repulsor", lane: "left")]),
                EncounterBeat(kind: "gap", frac: 0.18, slots: []),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "repulsor", lane: "right")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "moving", lane: "center")]),
                EncounterBeat(kind: "gap", frac: 0.55, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "wellWeave",
            family: "well",
            requires: ["blackhole", "moving", "shooting"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "blackhole", lane: "left"), EncounterSlot(type: "moving", lane: "right")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "shooting", lane: "right")]),
                EncounterBeat(kind: "gap", frac: 0.55, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "currentCut",
            family: "wind",
            requires: ["driftCurrent", "sweepGate"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "driftCurrent", lane: nil)]),
                EncounterBeat(kind: "gap", frac: 0.16, slots: []),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "sweepGate", lane: nil)]),
                EncounterBeat(kind: "gap", frac: 0.55, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "staggerSweeps",
            family: "sweep",
            requires: ["sweepGate"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "sweepGate", lane: nil)]),
                EncounterBeat(kind: "gap", frac: 0.22, slots: []),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "sweepGate", lane: nil)]),
                EncounterBeat(kind: "gap", frac: 0.55, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "moonCross",
            family: "complex",
            requires: ["complex", "shooting"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "complex", lane: "left"), EncounterSlot(type: "shooting", lane: "right")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "simple", lane: "center")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "moonLane",
            family: "complex",
            requires: ["complex", "moving"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "complex", lane: "left")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "moving", lane: "right")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "moonWall",
            family: "complex",
            requires: ["complex", "sideBarrier"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "sideBarrier", lane: nil)]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "complex", lane: "center")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "rockStorm",
            family: "rocks",
            requires: ["simple", "moving"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "simple", lane: "left"), EncounterSlot(type: "simple", lane: "center"), EncounterSlot(type: "simple", lane: "right")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "moving", lane: "center")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "simple", lane: "left"), EncounterSlot(type: "simple", lane: "right")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "pulseWeave",
            family: "pulse",
            requires: ["pulsating", "moving"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "pulsating", lane: "left")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "moving", lane: "right")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "simple", lane: "center")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "bloomDrift",
            family: "bloom",
            requires: ["phase", "moving"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "phase", lane: "center")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "moving", lane: "left")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "pushShot",
            family: "push",
            requires: ["repulsor", "shooting"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "repulsor", lane: "left"), EncounterSlot(type: "shooting", lane: "right")]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "simple", lane: "center")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "wellWind",
            family: "well",
            requires: ["blackhole", "driftCurrent"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "blackhole", lane: "left")]),
                EncounterBeat(kind: "gap", frac: 0.18, slots: []),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "driftCurrent", lane: nil)]),
                EncounterBeat(kind: "gap", frac: 0.55, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "sweepShot",
            family: "sweep",
            requires: ["sweepGate", "shooting"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "sweepGate", lane: nil)]),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "shooting", lane: "right")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        ),
        EncounterRecipe(
            id: "portalRocks",
            family: "portal",
            requires: ["wormhole", "complex"],
            beats: [
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "wormhole", lane: nil)]),
                EncounterBeat(kind: "gap", frac: 0.85, slots: []),
                EncounterBeat(kind: "spawn", frac: 0, slots: [EncounterSlot(type: "complex", lane: "center")]),
                EncounterBeat(kind: "gap", frac: 0.5, slots: [])
            ]
        )
    ]

    static let openSpacePairedFromKm: CGFloat = 2000
    static let openSpaceStormRepeatKm: CGFloat = 2500
    static let openSpaceStormDenseRepeatKm: CGFloat = 1500
    static let openSpaceStormDenseFromKm: CGFloat = 5000
    static let openSpaceDualStormFromKm: CGFloat = 12500
    static let openSpaceFullRosterKm: CGFloat = 7000
    static let openSpaceStormRepeatCount = 40
    static let openSpaceStormQuietFrac: CGFloat = 0.18
    static let openSpaceStormChainFrac: CGFloat = 0.08
    static let openSpaceStormGapCap: CGFloat = 0.28

    static let openSpaceWeather: [OpenSpaceWeatherBand] = [
        OpenSpaceWeatherBand(
            fromKm: 0,
            pair: nil,
            combo: nil,
            focus: nil
        ),
        OpenSpaceWeatherBand(
            fromKm: 1000,
            pair: "complex",
            combo: nil,
            focus: "complex"
        ),
        OpenSpaceWeatherBand(
            fromKm: 2000,
            pair: "moving",
            combo: nil,
            focus: "moving"
        ),
        OpenSpaceWeatherBand(
            fromKm: 3000,
            pair: "shooting",
            combo: "moving",
            focus: "shooting"
        ),
        OpenSpaceWeatherBand(
            fromKm: 4500,
            pair: "phase",
            combo: "shooting",
            focus: "phase"
        ),
        OpenSpaceWeatherBand(
            fromKm: 5500,
            pair: "repulsor",
            combo: "phase",
            focus: "repulsor"
        )
    ]

    static let openSpaceFullSky: [OpenSpaceSkyShift] = [
        OpenSpaceSkyShift(
            pair: "shooting",
            combo: "moving",
            focus: "complex"
        ),
        OpenSpaceSkyShift(
            pair: "phase",
            combo: "shooting",
            focus: "pulsating"
        ),
        OpenSpaceSkyShift(
            pair: "repulsor",
            combo: "phase",
            focus: "blackhole"
        ),
        OpenSpaceSkyShift(
            pair: "sweepGate",
            combo: "moving",
            focus: "sweepGate"
        ),
        OpenSpaceSkyShift(
            pair: "complex",
            combo: "pulsating",
            focus: "shooting"
        )
    ]

    static let openSpaceBelt: [OpenSpaceBeltBand] = [
        OpenSpaceBeltBand(
            fromKm: 0,
            minGapFrac: 0.22,
            gapSpread: 1.45,
            simpleChance: 0.55,
            density: 0.85,
            rowOne: 0.55,
            rowTwo: 0.88
        ),
        OpenSpaceBeltBand(
            fromKm: 5000,
            minGapFrac: 0.13,
            gapSpread: 1.25,
            simpleChance: 0.34,
            density: 1.7,
            rowOne: 0.18,
            rowTwo: 0.68
        ),
        OpenSpaceBeltBand(
            fromKm: 12500,
            minGapFrac: 0.11,
            gapSpread: 1.22,
            simpleChance: 0.26,
            density: 2.05,
            rowOne: 0.12,
            rowTwo: 0.62
        ),
        OpenSpaceBeltBand(
            fromKm: 20000,
            minGapFrac: 0.1,
            gapSpread: 1.2,
            simpleChance: 0.22,
            density: 2.15,
            rowOne: 0.1,
            rowTwo: 0.58
        )
    ]
}
